main:
  push:
    - imports: git@cnb.build:MornZe-Dev/secrets.git//main/github.yml
      docker:
        image: alpine/git
      stages:
        - script: |
            git remote add github https://${GITHUB_USER}:${GITHUB_TOKEN}@${GITHUB_REPO}
            git push github HEAD:${CNB_BRANCH} --force
